config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'test' ,to: 'testcascades#index'
  get 'create' ,to: 'createcascades#index'

  post 'upload_photo' , to: 'testcascades#upload_photo'

  get 'search_images' , to: 'createcascades#search_images', :defaults => { :format => 'json' }

  post 'createcascades' , to: 'createcascades#create_createcascades' 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/createcascades_controller.rb
class CreatecascadesController < ApplicationController
	def index
	end

	def search_images
		q = params[:get_images][:query]
		@images = Google::Search::Image.new(:query => q)
		respond_to do |format|
            # format.html {render 'index',object: @image_link}# show.html.erb
            format.json { render json: @images.as_json }
        end
	end

	def create_createcascades
		image_url = params[:optionsRadios]
		query = params[:createcascades][:object_name]
		image_name = image_url.split("/").last
		unless image_name.index("?").nil?
			image_name = image_name.slice 0..(image_name.index("?") - 1)
		end
		begin
			download = open(image_url)
			IO.copy_stream(download, Rails.root.join("public/tmp/#{query}", image_name))
			create_cascade image_name , query
			respond_to do |format|
				flash[:notice] = "Thank you, we working now to create your Cascade Classifier"	
				format.html {render 'index'}
			end
		rescue Exception => e
			respond_to do |format|
				flash[:notice] = "There is a problem Cascade Classifier"	
				format.html {render 'index'}
			end
		end
	end

	def create_cascade image_name , query
		# Check type of image
		type = image_name.split(".").last
		# Create samples from positve file
		res = Cascade::Classifier.createsamples image_name,type ,query
		# if true start the training
		if res
			return
			# Cascade::Classifier.training
		# else
		end
		
	end
end

app/controllers/testcascades_controller.rb
include OpenCV

class TestcascadesController < ApplicationController
	def index
		@classifier = Dir["lib/classifier/*.xml"].map {|x| x.split("/")[2]}
	end

	def upload_photo
        name =  params[:test][:datafile].original_filename
        cascades = params[:test][:classifier]
        directory = "public/data" # specify yr own path in public folder
        # create the file path
        path = File.join(directory, name)
        # write the file
        File.open(path, "wb") { |f| f.write(params[:test][:datafile].read) }
        if File.exist?(path)
        	@image_link = create_classifier(path,cascades)
        	flash[:notice] = "You have successfully upload to file."
    		respond_to do |format|
                format.html {render 'index',object: @image_link}# show.html.erb
                # format.json { render json: @adtag.as_json.merge({script: @ready_script})}
            end
    	else

            
    		flash[:notice] = "File can't upload try again."	
    	end
    end

    def create_classifier image_link , cascades
    	data = 'lib/classifier/' + cascades 
		detector = CvHaarClassifierCascade::load(data)
		image = CvMat.load(image_link)
		detector.detect_objects(image).each do |region|
		  color = CvColor::Blue
		  image.rectangle! region.top_left, region.bottom_right, :color => color
		end

		image.save_image(image_link)
        image_link.gsub("public/","")
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/createcascades/index.html.erb
<div class="container">
	<h1>Test the HAAR CLASSIFIER</h1>
	<br>
	<div class="row">
		<%= simple_form_for :get_images ,:method => "get",:url => 'search_images', :id=> "searchImages" ,:class => "box" ,remote: true do  |f| %>
			<div class="col-md-6">
				<div class="form-group">
					<label for="query">What object you want to look for?</label>
		    		<%= f.input "query", :class => "form-control required", :label => false,  :required => true %>
		    	</div>
		    	<button type="submit" id="getImages" class="btn ladda-button"><span class="ladda-label">Get images</span></button>
		    </div>
		<% end %>
	</div>
	<hr>
	<%= simple_form_for :createcascades ,:method => "post",:url => 'createcascades' do  |f| %>
		<div class="row">
			<%= f.input :object_name, :as => :hidden %>
			<div class="create col-md-12" hidden>
				Select the image for your object and then click here: 
				<button type="submit" class="btn btn-default " id="createHR" >Create Classifier</a>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-12 images"></div>
		</div>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Create', create_path %></li>
<li><%= link_to 'Test', test_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Image Processing" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Image Processing" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<h4>SAMPLES</h4>
	<p>
	In order to train our own classifier we need samples, which means we need a lot of images that show the object we want to detect (positive sample) and even more images without the object (negative sample).
	</p>
	<h5>POSITIVE IMAGES</h5>
	<p>we need to either take photos of the object we want to detect, it’s important that they should differ in lighting and background.</p>
	<h5>NEGATIVE IMAGES</h5>
	<p>We need the negative images, the ones that don’t show our object. In the best case, if we were to train a highly accurate classifier, we would have a lot of negative images that look exactly like the positive ones, except that they don’t contain the object we want to recognize. We need at least 600 of them</p>
	<h5>CREATING SAMPLES</h5>
	<p>With our positive and negative images in place, we are ready to generate samples out of them, which we will use for the training itself. We need positive and negative samples</p>
	<p>We’re going to use a method that doesn’t need a lot of preparation or a large number of positive or negative images. We’ll use a tool OpenCV gives us: opencv_createsamples. This tool offers several options as to how generate samples out of input images and gives us a *.vec file which we can then use to train our classifier.

	opencv_createsamples generates a large number of positive samples from our positive images, by applying transformations and distortions. Since one can only transform so much out of one image until it’s not a different version anymore, we need a little help to get a larger number of samples out of our relatively small number of input images.</p>
	<h5>TRAINING THE CLASSIFIER</h5>
	<p>OpenCV offers two different applications for training a Haar classifier: opencv_haartraining and opencv_traincascade. We are going to use opencv_traincascade since it allows the training process to be multi-threaded, reducing the time it takes to finish, and is compatible with the newer OpenCV 2.x API. Whenever you run into a problem when loading your classifier, make sure the application knows how to handle the format of the cascade file, since cascade files generated by opencv_haartraining and opencv_traincascade differ in format.</p>
</div>

app/views/testcascades/index.html.erb
<div class="container">
	<h1>Test the HAAR CLASSIFIER</h1>
	<br>
	<div class="row">
		<div class="col-md-6">
			<%= simple_form_for :test , :url => '/upload_photo', :multipart => true, :class => "box" , :html => { :enctype => "multipart/form-data" } do  |f| %>
				<div class="form-group">
			    	<%= f.file_field "datafile", :accept => "image/*", :class => "form-control required" %>
			    </div>
			    <div class="form-group">
			    	<%= f.input "classifier" , :collection => @classifier , :include_blank => false %>
			    </div>
			    <%= submit_tag "Upload" %>
			<% end %>
		</div>
		<div class="col-md-6">
			<% unless @image_link.nil? %>
				<img   width="500" src="<%= @image_link %>">
			<% end %>
		</div>
	</div>

</div>

app/views/visitors/index.html.erb
<div class="container">
	<h1>Cascade Classifier Training</h1>
	<hr>
	<h4>This application will demonstrate how to create your own OpenCV Haar classifier</h4>
	<h4>The idea is to give the user the option to recognize is own object in any image</h4>
</div>